Repository oleksandr-dehtiar-gl/gl-c-cpp-basecamp-2021-2, pull requests merged in 2022-01, with the labels that each got.

#30 Task 1
  01_network_sysapi/Client-Server_Mouse_check_app/.gitignore
  01_network_sysapi/Client-Server_Mouse_check_app/CMakeLists.txt
  01_network_sysapi/Client-Server_Mouse_check_app/CMakeLists.txt.user
  01_network_sysapi/Client-Server_Mouse_check_app/client/CMakeLists.txt
  01_network_sysapi/Client-Server_Mouse_check_app/client/main.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/main.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/CMakeLists.txt
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/message.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/messages.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/network.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/network.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/socket.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/network/socket.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/CMakeLists.txt
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/mouselocation.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/mouselocation.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/mousetracker.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/mousetracker.h
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/time.cpp
  01_network_sysapi/Client-Server_Mouse_check_app/modules/sys_api/time.h
  01_network_sysapi/Client-Server_Mouse_check_app/server/CMakeLists.txt
  01_network_sysapi/Client-Server_Mouse_check_app/server/main.cpp
  01_network_sysapi/WBS.md
Labels: task-1

#27 Task2
  .gitignore
  02_oop/CMakeLists.txt
  02_oop/gl_oop/LogicGates/andgate.cpp
  02_oop/gl_oop/LogicGates/andgate.h
  02_oop/gl_oop/LogicGates/logicinput.cpp
  02_oop/gl_oop/LogicGates/logicinput.h
  02_oop/gl_oop/LogicGates/nandgate.cpp
  02_oop/gl_oop/LogicGates/nandgate.h
  02_oop/gl_oop/LogicGates/norgate.cpp
  02_oop/gl_oop/LogicGates/norgate.h
  02_oop/gl_oop/LogicGates/notgate.cpp
  02_oop/gl_oop/LogicGates/notgate.h
  02_oop/gl_oop/LogicGates/orgate.cpp
  02_oop/gl_oop/LogicGates/orgate.h
  02_oop/gl_oop/LogicGates/xorgate.cpp
  02_oop/gl_oop/LogicGates/xorgate.h
  02_oop/gl_oop/LogicGatesGraphics/andgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/andgategraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/connection.cpp
  02_oop/gl_oop/LogicGatesGraphics/connection.h
  02_oop/gl_oop/LogicGatesGraphics/gndgraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/gndgraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/nandgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/nandgategraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/norgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/norgategraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/notgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/notgategraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/orgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/orgategraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/port.cpp
  02_oop/gl_oop/LogicGatesGraphics/port.h
  02_oop/gl_oop/LogicGatesGraphics/vccgraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/vccgraphicselement.h
  02_oop/gl_oop/LogicGatesGraphics/xorgategraphicselement.cpp
  02_oop/gl_oop/LogicGatesGraphics/xorgategraphicselement.h
  02_oop/gl_oop/elementtype.h
  02_oop/gl_oop/graphicselement.cpp
  02_oop/gl_oop/graphicselement.h
  02_oop/gl_oop/logicelement.cpp
  02_oop/gl_oop/logicelement.h
  02_oop/gl_oop/main.cpp
  02_oop/gl_oop/mainwindow.cpp
  02_oop/gl_oop/mainwindow.h
  02_oop/gl_oop/mainwindow.ui
  02_oop/gl_oop/scene.cpp
  02_oop/gl_oop/scene.h
  02_oop/gl_oop/workspace.cpp
  02_oop/gl_oop/workspace.h
Labels: task-2

#31 Kirill Timchenko. Task 3. WBS and diagrams
  03_qt_git/WBS.md
  03_qt_git/docs/diagrams/Class
  03_qt_git/docs/diagrams/Class.png
  03_qt_git/docs/diagrams/Sequence
  03_qt_git/docs/diagrams/Sequence.png
  03_qt_git/docs/diagrams/UseCase.drawio
  03_qt_git/docs/diagrams/UseCase.png
Labels: task-3

#22 Task2_1 kirill.timchenko
  02_oop/WBS.md
  02_oop/docs/diagrams/Class.drawio
  02_oop/docs/diagrams/Class.png
  02_oop/docs/diagrams/Sequence.drawio
  02_oop/docs/diagrams/Sequence.png
  02_oop/docs/diagrams/UseCase.drawio
  02_oop/docs/diagrams/UseCase.png
Labels: task-2

#28 add task 2
  02_oop/Documentation TASK_2.docx
  02_oop/ForTst1.txt
  02_oop/ForTst2.txt
  02_oop/ForTst3.txt
  02_oop/GL_TASK_2/GL_TASK_2.pro
  02_oop/GL_TASK_2/GL_TASK_2.pro.user
  02_oop/GL_TASK_2/main.cpp
  02_oop/GL_TASK_2/mainwindow.cpp
  02_oop/GL_TASK_2/mainwindow.h
  02_oop/GL_TASK_2/mainwindow.ui
  02_oop/GL_TASK_2/settingsSave.txt
  02_oop/Global_2/CMakeLists.txt
  02_oop/Global_2/CMakeLists.txt.user
  02_oop/Global_2/main.cpp
  02_oop/Global_2/mainwindow.cpp
  02_oop/Global_2/mainwindow.h
  02_oop/Global_2/mainwindow.ui
  02_oop/WBS.txt
  README.md
Labels: task-2
